### ISSUE TITLE
The ”earthformer-minimal /cfg_meteonet.yaml” file is missing

### ISSUE THREAD

**Issue by LeiShe1** [argenycw/FACL#1]
Your work is very good, can you provide this file

**Comment by argenycw** [comment]
Sorry that the file is missing. Could you please test if this works:
[cfg_meteonet.zip](https://github.com/user-attachments/files/17875186/cfg_meteonet.zip)

Thanks.

**Comment by LeiShe1** [comment]
Thank you very much
